import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "./components/ThemeProvider";
import BackgroundSwitcher from "./components/BackgroundSwitcher";

import { UserProvider } from "./context/UserContext";
import { TokenProvider } from "./context/TokenContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TokenProvider>
          <UserProvider>
            <ThemeProvider>
              <BackgroundSwitcher />
              {/* <Sidebar />
              <Header /> */}
              {children}
            </ThemeProvider>
          </UserProvider>
        </TokenProvider>
      </body>
    </html>
  );
}

// {/* <ThemeProvider>
//           <BackgroundSwitcher />
//           {/* <Sidebar />
//           <Header /> */}
//           {children}
// </ThemeProvider> */}